  grafana:
    image: grafana/grafana:${grafana_version}
    ports:
      - "3001:3000"
    volumes:
      - "./dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./dev-dashboards:/usr/share/grafana/devenv/dev-dashboards"
      - "./datasources_docker.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
